# Generated by Django 3.1.3 on 2021-04-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='blogcategory',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Music', 'Music'), ('Nature', 'Nature'), ('Education', 'Education'), ('Wedding', 'Wedding'), ('Travel', 'Travel'), ('Movie', 'Movie'), ('Car', 'Car'), ('Project', 'Project'), ('Photography', 'Photography'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
