# Generated by Django 3.1.3 on 2021-04-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210401_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[('PUB', 'Public'), ('PRI', 'Private')], max_length=120, null=True),
        ),
    ]
